plan/urls.py
from django.urls import path, register_converter
from . import views
from django.contrib.auth import views as auth_views

register_converter(views.DateConverter, 'date')


urlpatterns = [
    path('planEntry/<int:pk>/', views.planEntry, name='plan-Entry'),
    path('planEdit/<int:pk>/', views.planEdit, name='plan-Edit'),
    path('planEntryShow/<int:pk>/', views.plan_Entry_show, name='plan-Entry-show'),
    path('line/Plan/show/<int:pk>/', views.linePlan_show, name='line-Plan-Show'),
    path('Plan/layout/', views.Plan_layout, name='Plan-Layout'),
    path('Plan/layout/nav/<date:mydate>/',
         views.Plan_layout_nav, name='Plan-Layout-nav'),
    path('plan/forcast/', views.forcast_table, name='forcast-table'),
    path('plan/line/lock/<int:pk>/', views.plan_line_lock, name='plan-line-lock'),
    path('plan/line/move/<int:pk>/', views.plan_line_move, name='plan-line-move'),
    path('add/plan/<date:mydate>/', views.add_plan, name='add-plan'),
    path('style/', views.load_style, name='ajax_load_style'),  # AJAX
]

pper_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
#from dashboard.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    #path('home/', index)
    #path('dashboard/', views.index, name='dashboard-index'),
    #path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('home/', TemplateView.as_view(template_name='partials/home.html'), name='home'),
    path('', TemplateView.as_view(template_name='partials/web.html'), name='web'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True,
         template_name='commons/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='web'), name='logout'),
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='commons/change-password.html', success_url='/'), name='change_password'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='commons/password-reset/password_reset.html',
         subject_template_name='commons/password-reset/password_reset_subject.txt', email_template_name='commons/password-reset/password_reset_email.html',), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='commons/password-reset/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='commons/password-reset/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='commons/password-reset/password_reset_complete.html'), name='password_reset_complete'),
    path('setup/', include('setup.urls')),
    path('plan/', include('plan.urls')),
    path('production/', include('production.urls')),
    path('report/', include('report.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

plan/models.py
import datetime
from django.db import models
from django.utils import timezone
from setup.models import *
from django.contrib.auth.models import User
# Create your models here.

datastatus = (
    ('Y', 'YES'),
    ('N', 'NO'),
)


def increment_booking_number():
    last_booking = plan.objects.all().order_by('planID').last()
    if not last_booking:
        return 'PLN' + str(datetime.date.today().year) + str(datetime.date.today().month).zfill(2) + str(datetime.date.today().day).zfill(2) + '000'
    booking_id = last_booking.planID
    booking_int = int(booking_id[11:14])
    new_booking_int = booking_int + 1
    new_booking_id = 'PLN' + str(str(datetime.date.today().year)) + str(datetime.date.today(
    ).month).zfill(2) + str(datetime.date.today().day).zfill(2) + str(new_booking_int).zfill(3)
    return new_booking_id


class plan(models.Model):
    planID = models.CharField(
        max_length=150, default=increment_booking_number, null=True, unique=True)
    unit = models.ForeignKey(unit, models.CASCADE, null=True)
    buyer = models.ForeignKey(buyer, models.CASCADE, null=True)
    style = models.ForeignKey(style, models.CASCADE, null=True)
    line = models.ForeignKey(line, models.CASCADE, null=True)
    deleveryDate = models.DateField()
    sewingStartDate = models.DateField()
    sewingEndDate = models.DateField()
    orderQty = models.IntegerField()
    planQtyExtra = models.PositiveSmallIntegerField(default=3)
    totalOrder = models.IntegerField()
    linePlanQty = models.PositiveSmallIntegerField(default=0)
    estimateWorkDay = models.PositiveSmallIntegerField(default=0)
    #
    dataLock = models.CharField(
        max_length=2, default='N', choices=datastatus, null=True)
    staff = models.ForeignKey(User, models.CASCADE, null=True)
    created_at = models.DateField(default=timezone.now)
    modified = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.pk}'

plan/forms.py
from django import forms
from plan.models import plan
from production.models import production
from setup.models import *
##


class PlanForm(forms.ModelForm):
    buyer = forms.ModelChoiceField(queryset=buyer.objects.order_by('name'))
    style = forms.ModelChoiceField(queryset=style.objects.order_by('name'))

    class Meta:
        model = plan
        fields = ['buyer', 'style', 'deleveryDate', 'sewingStartDate',
                  'sewingEndDate', 'orderQty', 'planQtyExtra']
        widgets = {
            'deleveryDate': forms.DateInput({'type': 'date'}),
            'sewingStartDate': forms.DateInput({'type': 'date'}),
            'sewingEndDate': forms.DateInput({'type': 'date'}),
        }
        labels = {
            'deleveryDate': 'Delevery Date',
            'sewingStartDate': 'Sewing Start Date',
            'sewingEndDate': 'Sewing End Date',
            'orderQty': 'Order Qty.',
            'planQtyExtra': 'Plan Qty. Extra',
        }

        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['style'].queryset = style.objects.none()

            if 'buyer' in self.data:
                try:
                    buyer = int(self.data.get('buyer'))
                    self.fields['style'].queryset = style.objects.filter(
                        buyer=buyer).order_by('name')
                except (ValueError, TypeError):
                    pass  # invalid input from the client; ignore and fallback to empty City queryset
            elif self.instance.pk:
                self.fields['style'].queryset = self.instance.buyer.style_set.order_by(
                    'name')


class planAddForms(forms.ModelForm):
    line = forms.ModelChoiceField(queryset=line.objects.order_by('name'))

    class Meta:
        model = production
        fields = ['line', 'style', 'operator', 'helper',
                  'runDay', 'workHour', 'dayTarget']

plan/views.py
from django.contrib.auth.decorators import login_required
from datetime import date, datetime, timedelta
from django.shortcuts import render
from django.contrib import messages
from plan.forms import PlanForm, planAddForms
from django.shortcuts import render, redirect
from plan.models import plan
from production.models import production
from django.forms import modelformset_factory


from setup.models import style, line
# Create your views here.

# ((Output*SMV)/(Manpower*(Working*60)))*100


def EfficiencyCaculator(Output, SMV, Manpower, WorkingHour):
    if float(SMV) > 0 and Manpower > 0 and WorkingHour > 0 and Output > 0:
        Efficiency = ((Output*SMV)/(Manpower*(WorkingHour*60))) * 100
    return Efficiency


class DateConverter:
    regex = '\d{4}-\d{1,2}-\d{1,2}'
    format = '%Y-%m-%d'

    def to_python(self, value):
        return datetime.strptime(value, self.format).date()

    def to_url(self, value):
        return value.strftime(self.format)


def unitKnow(request):
    unitKnow = request.user.profile.unit
    return unitKnow


def findOutDate(anyDay):
    curentDay = curentDay = date.today()
    nextDay = anyDay + timedelta(days=1)
    lastDay = anyDay - timedelta(days=1)
    return lastDay, curentDay, nextDay

# percentage To Amount 3% 103


def percentageToAmount(amount, percentage):
    amountValue = round(((amount*percentage)/100)+amount)
    # print(amountValue)
    return amountValue

# date check of plan from


def planDate(deleveryDate, sewingStartDate, sewingEndDate):
    toDay = date.today()
    datePass = False
    nextDay = toDay + timedelta(days=180)
    peviousDay = toDay - timedelta(days=14)
    if sewingStartDate < nextDay and sewingStartDate > peviousDay:
        datePass = True
    else:
        datePass = False
    if sewingEndDate < nextDay and sewingEndDate > peviousDay and sewingEndDate >= sewingStartDate:
        datePass = True
    else:
        datePass = False
    if deleveryDate < nextDay and deleveryDate > peviousDay:
        if deleveryDate >= sewingStartDate and deleveryDate >= sewingEndDate:
            datePass = True
        else:
            datePass = False
    else:
        datePass = False
    return datePass

# finout amoun of day


def planBook(sewingStartDate, sewingEndDate):
    planForDay = sewingEndDate - sewingStartDate
    planForDay = (planForDay.days)+1
    return planForDay

# depandency drop down menu


def load_style(request):
    buyer = request.GET.get('buyer')
    styles = style.objects.filter(buyer=buyer).all()
    return render(request, 'plan/style_load.html', {'styles': styles})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)


@login_required
def planEntry(request, pk):
    lineData = line.objects.get(pk=pk)
    weekend = lineData.unit.holiday
    # print(weekend)
    if request.method == 'POST':
        form = PlanForm(request.POST)
        if form.is_valid():
            planData = form.save(commit=False)
            datePass = planDate(planData.deleveryDate,
                                planData.sewingStartDate, planData.sewingEndDate)
            if planData.orderQty > 0 and datePass is True:
                planForDay = planBook(planData.sewingStartDate,
                                      planData.sewingEndDate)
                sewingDate = planData.sewingStartDate
                planData.unit = lineData.unit
                planData.line = lineData
                planData.totalOrder = percentageToAmount(
                    planData.orderQty, planData.planQtyExtra)
                planData.staff = request.user
                planData.save()
                for x in range(planForDay):
                    dayName = sewingDate.weekday()
                    if int(weekend) != int(dayName):
                        productionPlan = production()
                        productionPlan.sewingDate = sewingDate
                        productionPlan.unit = lineData.unit
                        productionPlan.planID = planData.planID
                        productionPlan.plan = planData
                        productionPlan.style = planData.style
                        productionPlan.line = planData.line
                        productionPlan.floor = planData.line.floor
                        productionPlan.staff = request.user
                        productionPlan.save()
                    sewingDate += timedelta(days=1)
                messages.success(
                    request, 'Successful, Plan Add in PPER System')
                return redirect('plan-Entry-show', planData.pk)
            else:
                messages.warning(
                    request, 'Unsuccessful, Order Quy. Cannot Zero and check Date')
        else:
            form = PlanForm()
            messages.warning(
                request, 'Unsuccessful, Plan Cannot Add in PPER System')
    else:
        form = PlanForm()
    context = {
        'form': form,
        'pk': pk,
        'lineName': lineData.name,
    }
    return render(request, 'plan/planEntry.html', context)


def planEdit(request, pk):
    # lineData = line.objects.get(pk=pk)
    planData = plan.objects.get(id=pk)
    productionData = production.objects.filter(plan=pk, dataLock='N')
    if request.method == 'POST':
        form = PlanForm(request.POST, instance=planData)
        if form.is_valid():
            planData = form.save(commit=False)
            datePass = planDate(planData.deleveryDate,
                                planData.sewingStartDate, planData.sewingEndDate)
            if planData.orderQty > 0 and planData.planQtyExtra < 10 and datePass is True:
                planData.totalOrder = percentageToAmount(
                    planData.orderQty, planData.planQtyExtra)
                planData.buyer = planData.style.buyer
                planData.staff = request.user
                planData.save()
                for productions in productionData:
                    productions.style = planData.style
                    productions.save()
                messages.success(
                    request, 'Successful, Plan Update in PPER System')
                return redirect('plan-Entry-show', planData.pk)
            else:
                form = PlanForm(instance=planData)
                messages.warning(
                    request, 'unsuccessful, please set 3 Qty.Extra field')
    else:
        form = PlanForm(instance=planData)
    context = {
        'form': form,
        'pk': pk,
        'lineName': planData.line.name,

    }
    return render(request, 'plan/planEdit.html', context)


def plan_Entry_show(request, pk):
    planSummary = plan.objects.get(pk=pk)
    planDetail = production.objects.filter(plan=pk).order_by('sewingDate')
    context = {
        'planSummary': planSummary,
        'planDetail': planDetail,

    }
    return render(request, 'plan/planEntryShow.html', context)


def linePlan_show(request, pk):
    planSummary = plan.objects.all().filter(line=pk).order_by('sewingStartDate')
    context = {
        'planSummary': planSummary,
        # 'planDetail': planDetail,
    }
    return render(request, 'plan/linePlanShow.html', context)


def forcast_table(request):
    pk = request.user.profile.unit
    planSummary = plan.objects.all().filter(unit=pk).order_by('sewingStartDate')
    context = {
        'planSummary': planSummary,
        # 'planDetail': planDetail,
    }
    return render(request, 'plan/linePlanShow.html', context)


'''


def Plan_layout(request):

    context = {

    }
    return render(request, 'plan/plan_layout.html', context)


'''


def Plan_layout_day(unit, dateData):
    productionData = production.objects.filter(
        sewingDate=dateData, unit__id=unit).order_by('line')
    return productionData


def Plan_layout_nav(request, mydate):
    unit = unitKnow(request)
    lastDay, curentDay, nextDay = findOutDate(mydate)
    productionData = Plan_layout_day(unit.id, mydate)
    goToPage = 'Plan-Layout-nav'
    context = {
        'production': productionData,
        'lastDay': lastDay,
        'curentDay': curentDay,
        'nextDay': nextDay,
        'goToPage': goToPage,
        'mydate': mydate,
    }
    return render(request, 'plan/plan_layout.html', context)


def Plan_layout(request):
    unit = unitKnow(request)
    mydate = date.today()
    lastDay, curentDay, nextDay = findOutDate(mydate)
    goToPage = 'Plan-Layout-nav'
    productionData = Plan_layout_day(unit.id, mydate)
    context = {
        'production': productionData,
        'lastDay': lastDay,
        'curentDay': curentDay,
        'nextDay': nextDay,
        'goToPage': goToPage,
        'mydate': mydate,
    }
    return render(request, 'plan/plan_layout.html', context)


def plan_line_lock(request, pk):
    productionData = production.objects.get(pk=pk)
    mydate = productionData.sewingDate
    if productionData.dataLock == 'Y':
        productionData.dataLock = 'N'
        # productionData.save()
        # return redirect('plan-Entry-show', productionData.plan)
    else:
        productionData.dataLock = 'Y'
    productionData.save()
    return redirect('Plan-Layout-nav', mydate)


def plan_line_move(request, pk):
    productionData = production.objects.get(pk=pk)
    weekend = productionData.unit.holiday
    mydate = productionData.sewingDate
    planData = plan.objects.get(pk=productionData.plan.id)
    anyDay = planData.sewingEndDate
    lastDay, curentDay, nextDay = findOutDate(anyDay)
    dayName = nextDay.weekday()
    if int(weekend) != int(dayName):
        productionData.sewingDate = nextDay
        planData.sewingEndDate = nextDay
        planData.save()
        productionData.save()
    else:
        lastDay, curentDay, nextDay = findOutDate(nextDay)
        productionData.sewingDate = nextDay
        planData.sewingEndDate = nextDay
        planData.save()
        productionData.save()
    return redirect('Plan-Layout-nav', mydate)


def add_plan(request, mydate):
    unit = unitKnow(request)

templates/plan/add_plan copy 2.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% block title %}Line Plan Summary{% endblock title %} 
{% load crispy_forms_tags %}
{% block css %}<link rel="stylesheet" href="{% static 'css/plan/add_plan.css' %}" />{% endblock css %}  
{% block content %}
<div class="add-Plan block-content">
    <div class="messages">
        {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
        {% endif %}
      </div>
    <h3 class="page-heading">Add Plan | {{mydate}}</h3>
    <div class="card">
        <div class="card-container">
          <form method="post">
            {% csrf_token %}
            {{ formset.management_form }}
            <table>
              <thead>
              {% for forms in formset %}
                  {% csrf_token %}
                  {% for hidden in forms.hidden_fields %}
                      {{ hidden }}
                  {% endfor %}
                  {{ formset.non_field_errors }}
                  {% if forloop.first %}
                    {% for field in forms %}
                        <th>{{ field.label_tag }}</th>
                    {% endfor %}
                  {% endif %}
                </thead>
                <tbody>
                        <tr>
                            {% for field in forms %}
                                <td>{{ field }}</td>
                            {% endfor %}
                        </tr>
                {% endfor %}
                </tbody>
              </table>
          <div class="button_container">
            <button type="Cancel" class="button btn-red btn-r12" ><a style="color:white" href="{% url 'Plan-Layout-nav' mydate %}">Cancel</a></button>
            <button type="submit" class="button btn-green btn-r12" >Apply Now</button>
          </div>
        </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/plan/add_plan copy.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% block title %}Line Plan Summary{% endblock title %} 
{% load crispy_forms_tags %}
{% block css %}<link rel="stylesheet" href="{% static 'css/plan/add_plan.css' %}" />{% endblock css %}  
{% block content %}
<div class="add-Plan block-content">
    <div class="messages">
        {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
        {% endif %}
      </div>
    <h3 class="page-heading">Add Plan | {{mydate}}</h3>
    <div class="card">
        <div class="card-container">
          <form method="post">
            {% csrf_token %}
            {{ formset.management_form }}
            {% for forms in formset %}
                {% csrf_token %}
                {% for hidden in forms.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {{ formset.non_field_errors }}
                <tr>
                    <td>{{ forms.operator }}</td>
                    <td>{{ forms.helper }}</td>
                    <td>{{ forms.runDay }}</td>
                    <td>{{ forms.workHour }}</td>
                    <td>{{ forms.dayTarget }}</td>
                </tr>
            {% endfor %}
          <div class="button_container">
            <button type="Cancel" class="button btn-red btn-r12" ><a style="color:white" href="{% url 'Plan-Layout-nav' mydate %}">Cancel</a></button>
            <button type="submit" class="button btn-green btn-r12" >Apply Now</button>
          </div>
        </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/plan/add_plan.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% block title %}Line Plan Summary{% endblock title %} 
{% load crispy_forms_tags %}
{% block css %}<link rel="stylesheet" href="{% static 'css/plan/add_plan.css' %}" />{% endblock css %}  
{% block content %}
<div class="add-Plan block-content">
    <div class="messages">
        {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
        {% endif %}
      </div>
    
    <div class="card">
      <h3 class="page-heading">Add Plan | {{mydate}}</h3>
        <div class="card-container">
          <form method="post" class="addPlanForm">
            {% csrf_token %}
            {{ formset.management_form }}
            <table>
              <thead>
                <tr>
                  <td class="line-num">line</td>
                  <td class="B-style">style</td>
                  <td>operator</td>
                  <td>helper</td>
                  <td>run Day</td>
                  <td>work Hour</td>
                  <td>day Target</td>
                </tr>
              </thead>
              <tbody>
              {% for forms in formset %}
                  {% csrf_token %}
                                                              {% for hidden in forms.hidden_fields %}
                                                                  {{ hidden }}
                                                              {% endfor %}
                                                              {{ formset.non_field_errors }}
                
                
                        <tr>
                            {% for field in forms %}
                                <td>{{ field}}</td>
                            {% endfor %}
                        </tr>
                {% endfor %}
                </tbody>
              </table>
          <div class="button_container">
            <button type="Cancel" class="button btn-red btn-r12" ><a style="color:white" href="{% url 'Plan-Layout-nav' mydate %}">Cancel</a></button>
            <button type="submit" class="button btn-green btn-r12" >Apply Now</button>
          </div>
        </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/plan/linePlanShow.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% block title %}Line Plan Summary{% endblock title %} 
{% load crispy_forms_tags %}
{% block css %}<link rel="stylesheet" href="{% static 'css/plan/linePlanShow.css' %}" />{% endblock css %}  
{% block content %}
<div class="line-Plan-Show block-content">
    <div class="messages">
        {% if messages %}
        {% for message in messages %}
          <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
        {% endif %}
      </div>
    <div class="planSummary-area"> 
        <h3>Line Plan Forcast</h3>
        <table class="table">
            <tr>
               <th class="line-num">Line</th>
               <th>Buyer</th>
               <th class="B-style">Style</th>
               <th>Sewing Start Date</th>
               <th>Sewing End Date</th>
               <th>Delevery Date</th>
               <th>Action</th>
            </tr>
            {% for planSummarys in planSummary%}
            <tr>
                <td>{{planSummarys.line}}</td>
                <td>{{planSummarys.buyer}}</td>
                <td>{{planSummarys.style}}</td>
                <td>{{planSummarys.sewingStartDate}}</td>
                <td>{{planSummarys.sewingEndDate}}</td>
                <td>{{planSummarys.deleveryDate}}</td>
                <td><a href="{% url 'plan-Entry-show' planSummarys.id %}" class="button btn-green btn-r12">View</a></td>
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock content %}

templates/plan/planEdit.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% block title %}planEntry{% endblock title %} 
{% load crispy_forms_tags %}
{% block css %}<link rel="stylesheet" href="{% static 'css/plan/planEntry.css' %}" />{% endblock css %}  
{% block content %}
<div class="plan-Entry block-content">
  <div class="messages">
    {% if messages %}
    {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
    {% endif %}
  </div>
  <div class="card">
    <div class="card-container">
      <h4 class="card-title"><b>Line {{lineName}}</b></h4>
      <form method="POST" id="personForm" data-styles-url="{% url 'ajax_load_style' %}">
        {% csrf_token %}
      <div class="form_container-grid">
        <div class="form_control">
          {{ form.buyer|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.style|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.deleveryDate|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.sewingStartDate|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.sewingEndDate|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.orderQty|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.planQtyExtra|as_crispy_field}}
        </div>
      </div>
      <div class="button_container">
        <button type="Cancel" class="button btn-red btn-r12" ><a style="color:white" href="{% url 'home' %}">Cancel</a></button>
        <button type="submit" class="button btn-green btn-r12" >Apply Now</button>
      </div>
    </form>  
    </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_buyer").change(function () {
        const url = $("#personForm").attr("data-styles-url");  // get the url of the `load_cities` view
        const buyerId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'buyer': buyerId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_style").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>
{% endblock content %}

templates/plan/planEntry.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% block title %}planEntry{% endblock title %} 
{% load crispy_forms_tags %}
{% block css %}<link rel="stylesheet" href="{% static 'css/plan/planEntry.css' %}" />{% endblock css %}  
{% block content %}
<div class="plan-Entry block-content">
  <div class="messages">
    {% if messages %}
      {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
      {% endfor %}
    {% endif %}
  </div>
  <div class="card">
    <div class="card-container">
      <h4 class="card-title"><b>Line {{lineName}}</b></h4>
      <form method="POST" id="personForm" data-styles-url="{% url 'ajax_load_style' %}">
        {% csrf_token %}
      <div class="form_container-grid">
        <div class="form_control">
          {{ form.buyer|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.style|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.deleveryDate|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.sewingStartDate|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.sewingEndDate|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.orderQty|as_crispy_field}}
        </div>
        <div class="form_control">
          {{ form.planQtyExtra|as_crispy_field}}
        </div>
      </div>
      <div class="button_container">
        <button type="Cancel" class="button btn-red btn-r12" ><a style="color:white" href="{% url 'home' %}">Cancel</a></button>
        <button type="submit" class="button btn-green btn-r12" >Apply Now</button>
      </div>
    </form>  
    </div>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_buyer").change(function () {
        const url = $("#personForm").attr("data-styles-url");  // get the url of the `load_cities` view
        const buyerId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'buyer': buyerId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_style").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>
{% endblock content %}

templates/plan/style_load.html
<option value="">---------</option>
{% for style in styles %}
<option value="{{ style.pk }}">{{ style.name }}</option>
{% endfor %}