plan/urls.py
from django.urls import path, register_converter
from . import views
from django.contrib.auth import views as auth_views

register_converter(views.DateConverter, 'date')


urlpatterns = [
    path('planEntry/<int:pk>/', views.planEntry, name='plan-Entry'),
    path('planEdit/<int:pk>/', views.planEdit, name='plan-Edit'),
    path('planEntryShow/<int:pk>/', views.plan_Entry_show, name='plan-Entry-show'),
    path('line/Plan/show/<int:pk>/', views.linePlan_show, name='line-Plan-Show'),
    path('Plan/layout/', views.Plan_layout, name='Plan-Layout'),
    path('Plan/layout/nav/<date:mydate>/',
         views.Plan_layout_nav, name='Plan-Layout-nav'),
    path('plan/forcast/', views.forcast_table, name='forcast-table'),
    path('plan/line/lock/<int:pk>/', views.plan_line_lock, name='plan-line-lock'),
    path('plan/line/move/<int:pk>/', views.plan_line_move, name='plan-line-move'),
    path('add/plan/<date:mydate>/', views.add_plan, name='add-plan'),
    path('style/', views.load_style, name='ajax_load_style'),  # AJAX
]

pper_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView
#from dashboard.views import index


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    #path('home/', index)
    #path('dashboard/', views.index, name='dashboard-index'),
    #path('home/', TemplateView.as_view(template_name='home.html'), name='home'),
    path('home/', TemplateView.as_view(template_name='partials/home.html'), name='home'),
    path('', TemplateView.as_view(template_name='partials/web.html'), name='web'),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True,
         template_name='commons/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='web'), name='logout'),
    path('change-password/', auth_views.PasswordChangeView.as_view(
        template_name='commons/change-password.html', success_url='/'), name='change_password'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='commons/password-reset/password_reset.html',
         subject_template_name='commons/password-reset/password_reset_subject.txt', email_template_name='commons/password-reset/password_reset_email.html',), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='commons/password-reset/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='commons/password-reset/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name='commons/password-reset/password_reset_complete.html'), name='password_reset_complete'),
    path('setup/', include('setup.urls')),
    path('plan/', include('plan.urls')),
    path('production/', include('production.urls')),
    path('report/', include('report.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

setup/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('buyer/list', views.buyer_list,
         name='buyer-list'),  # List and Add Buyer
    path('buyer/edit/<int:pk>/', views.buyer_edit,
         name='buyer-edit'),  # List and Edit Buyer
    path('style/list', views.style_list,
         name='style-list'),  # List and Add Buyer
    path('style/edit/<int:pk>/', views.style_edit,
         name='style-edit'),  # List and Edit Buyer
]

setup/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
holiday = (
    ('6', 'Sunday'),
    ('0', 'Monday'),
    ('1', 'Tuesday'),
    ('2', 'Wednesday'),
    ('3', 'Thursday'),
    ('4', 'Friday'),
    ('5', 'Saturday'),
)


class Department(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.name}'


class userType(models.Model):
    typeName = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return f'{self.typeName}'


class unit(models.Model):
    name = models.CharField(max_length=50, unique=True)
    shortcut = models.CharField(max_length=6, unique=True)
    address = models.CharField(max_length=100)
    holiday = models.CharField(max_length=1, choices=holiday)
    startDuty = models.PositiveSmallIntegerField(null=True, default=8)
    endDuty = models.PositiveSmallIntegerField(null=True, default=17)

    def __str__(self):
        return f'{self.name}'


class buyer(models.Model):
    name = models.CharField(max_length=50, unique=True)
    shortcut = models.CharField(max_length=8, unique=True)
    address = models.CharField(max_length=100)
    created_at = models.DateField(default=timezone.now)

    def __str__(self):
        return f'{self.name}'


class style(models.Model):
    name = models.CharField(max_length=50, unique=True)
    buyer = models.ForeignKey(buyer, models.CASCADE, null=True)
    smv = models.DecimalField(max_digits=5, decimal_places=3)
    created_at = models.DateField(default=timezone.now)
    modified = models.DateField(auto_now=True)

    def __str__(self):
        return f'{self.name}'


class floor(models.Model):
    name = models.CharField(max_length=50, unique=True)
    unit = models.ForeignKey(unit, models.CASCADE, null=True)

    def __str__(self):
        return f'{self.name}'


class line(models.Model):
    name = models.CharField(max_length=50, unique=True)
    floor = models.ForeignKey(floor, models.CASCADE, null=True)
    unit = models.ForeignKey(unit, models.CASCADE, null=True)

    def __str__(self):
        return f'{self.name}'

setup/forms.py
from django import forms

from setup.models import *


##
class BuyerForm(forms.ModelForm):
    class Meta:
        model = buyer
        labels = {
            'name': '',
            'shortcut': '',
            'address': '',
        }
        fields = [
            'name',
            'shortcut',
            'address',
        ]


class StyleForm(forms.ModelForm):
    class Meta:
        model = style
        labels = {
            'name': '',
            'buyer': '',
            'smv': '',
        }
        fields = [
            'name',
            'buyer',
            'smv',
        ]

setup/views.py
import datetime
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from setup.forms import *
from setup.models import buyer, style
from django.contrib import messages
from datetime import date, timedelta
from django.db.models import Q


def dateFind():
    toDay = date.today()
    last7Day = toDay - timedelta(days=45)
    date7Range = Q(created_at__range=[last7Day, toDay])
    return date7Range


def buyerStatus():
    date7Range = dateFind()
    Buyer = buyer.objects.all().order_by('name')
    totalBuyer = Buyer.count()
    newBuyer = Buyer.filter(date7Range).count()
    return Buyer, newBuyer, totalBuyer


def styleStatus():
    date7Range = dateFind()
    Style = style.objects.all().order_by('-created_at')
    totalStyle = Style.count()
    newStyle = Style.filter(date7Range).count()
    return Style, newStyle, totalStyle


'''
def date_default():
    enddate = date.today()
    startdate = enddate - timedelta(days=45)
    dateQ = Q(date__range=[startdate, enddate])
    return dateQ


def date_enddate(enddate):
    if not enddate:
        enddate = date.today()
    else:
        enddate = datetime.strptime(enddate, "%m/%d/%Y").strftime('%Y-%m-%d')
    return enddate


def date_startdate(startdate):
    if not startdate:
        startdate = '2021-06-01'
    else:
        startdate = datetime.strptime(
            startdate, "%m/%d/%Y").strftime('%Y-%m-%d')
    return startdate
'''


def buyer_list(request):
    Buyer, newBuyer, totalBuyer = buyerStatus()
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = BuyerForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # print(form)
            # return HttpResponseRedirect('buyer-list')
            form.save()
            messages.success(request, 'Successful, Buyer Add in PPER System')
            return redirect('buyer-list')
        else:
            form = BuyerForm()
            messages.warning(
                request, 'Unsuccessful, Buyer Cannot Add in PPER System')
    # if a GET (or any other method) we'll create a blank form
    else:
        form = BuyerForm()
    context = {
        'Buyers': Buyer,
        'form': form,
        'totalBuyer': totalBuyer,
        'newBuyer': newBuyer,
    }
    return render(request, 'setup/buyerListAdd.html', context)


def buyer_edit(request, pk):
    Buyer, newBuyer, totalBuyer = buyerStatus()
    BuyerEdit = buyer.objects.get(id=pk)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = BuyerForm(request.POST, instance=BuyerEdit)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # print(form)
            # return HttpResponseRedirect('buyer-list')
            form.save()
            messages.success(request, 'Successful, Buyer Add in PPER System')
            return redirect('buyer-list')
        else:
            messages.warning(
                request, 'Unsuccessful, Buyer Cannot Add in PPER System')
    # if a GET (or any other method) we'll create a blank form
    else:
        form = BuyerForm(instance=BuyerEdit)
    context = {
        'Buyers': Buyer,
        'totalBuyer': totalBuyer,
        'newBuyer': newBuyer,
        'form': form,
        'pk': pk,
    }
    return render(request, 'setup/buyerListEdit.html', context)


def style_list(request):
    Style, newStyle, totalStyle = styleStatus()
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = StyleForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # print(form)
            # return HttpResponseRedirect('buyer-list')
            form.save()
            messages.success(request, 'Successful, Style Add in PPER System')
            return redirect('style-list')
        else:
            form = StyleForm()
            messages.warning(
                request, 'Unsuccessful, Style Cannot Add in PPER System')
    # if a GET (or any other method) we'll create a blank form
    else:
        form = StyleForm()
    context = {
        'Style': Style,
        'form': form,
        'newStyle': newStyle,
        'totalStyle': totalStyle,
    }
    return render(request, 'setup/styleListAdd.html', context)


def style_edit(request, pk):
    Style, newStyle, totalStyle = styleStatus()
    StyleEdit = style.objects.get(id=pk)
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = StyleForm(request.POST, instance=StyleEdit)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            # print(form)
            # return HttpResponseRedirect('buyer-list')
            form.save()
            messages.success(request, 'Successful, Style Add in PPER System')
            return redirect('style-list')
        else:
            messages.warning(
                request, 'Unsuccessful, Buyer Cannot Add in PPER System')
    # if a GET (or any other method) we'll create a blank form
    else:
        form = StyleForm(instance=StyleEdit)
    context = {
        'Style': Style,
        'form': form,
        'pk': pk,
        'newStyle': newStyle,
        'totalStyle': totalStyle,
    }
    return render(request, 'setup/styleListEdit.html', context)


'''
def buyer_edit(request, pk):
    Buyer = buyer.objects.all().order_by('name')
    BuyerEdit = buyer.objects.get(id=pk)
    form = BuyerForm()
    context = {
        'Buyers': Buyer,
        'form': form,
    }
    return render(request, 'setup/buyerList.html', context)

'''
'''
    def buyerlist(request):
    clientDATA = Buyer.objects.all().order_by('name')
    if request.method == 'POST':
        form = BuyerForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('fslplan-buyer-list')
    else:
        form = BuyerForm()
    context = {
        'form': form,
        'clientDATA': clientDATA,
    }
    return render(request, 'fslplan/buyer_list.html', context)
'''

templates/setup/buyerList.html
{% extends 'base.html' %}
{% load static %} 
{% block title %}Login Page {% endblock title %}
{% load crispy_forms_tags %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/addList.css' %}" />
<div class="container">
    <div class="add-area">
        <div class="add_box">
        </div>    
    </div>
    <div class="list-area">
      <div class="buyerAdd">
        <button class="open-button" onclick="openForm()">Open Form</button>
        <div class="form-popup" id="myForm">
          <form action="/action_page.php" class="form-container">
            <h1>Login</h1>

            <label for="email"><b>Email</b></label>
            <input type="text" placeholder="Enter Email" name="email" required>

            <label for="psw"><b>Password</b></label>
            <input type="password" placeholder="Enter Password" name="psw" required>

            <button type="submit" class="btn">Login</button>
            <button type="button" class="btn cancel" onclick="closeForm()">Close</button>
          </form>
        </div>











      </div>
        <table style="width:100%">
          <tr>
            <th style="width:5%">SL</th>
            <th style="width:45%">Buyer</th>
            <th style="width:15%">Shortcut</th>
            <th style="width:20%">Address</th>
            <th style="width:15%">Action</th>
          </tr>
          {% for Buyer in Buyers %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{Buyer.name}}</td>
            <td>{{Buyer.shortcut}}</td>
            <td>{{Buyer.address}}</td>
            <td></td>
          </tr>
          {% endfor%}
        </table>
    </div>
</div>
<script src="{% static 'js/addForm.js' %}"></script>
{% endblock%}

templates/setup/buyerListAdd.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% block title %}Buyer Page{% endblock title %}
{% load crispy_forms_tags %}
{% block css %}<link rel="stylesheet" href="{% static 'css/setup/buyerListAdd.css' %}" />{% endblock css %}  
{% block content %}

<div class="buyer-add-edit block-content">
  <div class="messages">
    {% if messages %}
    {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
    {% endif %}
  </div>
  <div class="hero_box">
    <div class="add-buyer form_box">
      <h3 class="form-title"><a href="#" class="open-button" onclick="openForm()">Add Buyer</a></h3>
      <div id="myForm">
          <form method="POST">
            {% csrf_token %}
          <div class="form_container-grid">
            <div class="form_control">
              <label for="id_name"> Buyer Name </label>
              {{ form.name|as_crispy_field}}
            </div>
            <div class="form_control">
              <label for="id_shortcut"> Short Name </label>
              {{ form.shortcut|as_crispy_field}}
            </div>
            <div class="form_control">
              <label for="id_address"> Address </label>
              {{ form.address|as_crispy_field}}
            </div>
          </div>
          <div class="button_container">
            <button type="submit" class="button btn-green btn-r12" >Apply Now</button>
          </div>
        </form>
      </div>
    </div>
    <div class="card-area">
      <div class="card">
        <div class="card-container">
          <h4 class="card-title"><b>New Buyer</b></h4> 
          <p class="card-description">{{newBuyer}}</p> 
        </div>
      </div>
      <div class="card">
        <div class="card-container">
          <h4 class="card-title"><b>Total Buyer</b></h4> 
          <p class="card-description">{{totalBuyer}}</p> 
        </div>
      </div>
    </div>
  </div>
  <div class="list-area">
    <table class="table"style="width:100%">
        <tr>
            <th style="width:5%">SL</th>
            <th style="width:45%">Buyer</th>
            <th style="width:15%">Shortcut</th>
            <th style="width:20%">Address</th>
            <th style="width:15%">Action</th>
          </tr>
          {% for Buyer in Buyers %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{Buyer.name}}</td>
            <td>{{Buyer.shortcut}}</td>
            <td>{{Buyer.address}}</td>
            <td><a href="{% url 'buyer-edit' Buyer.pk%}" class="button btn-green btn-r12 by-edit">Edit</a></td>
          </tr>
          {% endfor%}
        </table>
  </div>
</div>
<script src="{% static 'js/buyerListAdd.js' %}"></script>
{% endblock content %}

templates/setup/buyerListEdit.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% block title %}Buyer Page{% endblock title %}
{% load crispy_forms_tags %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/setup/buyerListAdd.css' %}" />
  <link rel="stylesheet" href="{% static 'css/setup/buyerListEdit.css' %}" />
{% endblock css %}  
{% block content %}
<div class="buyer-add-edit">
  <div class="messages">
    {% if messages %}
    {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
    {% endif %}
  </div>
  <div class="hero_box">
    <div class="add-buyer form_box">
      <h3 class="form-title"><a href="#" class="open-button" onclick="openForm()">Update Buyer</a></h3>
      <div id="myForm">
          <form method="POST">
            {% csrf_token %}
          <div class="form_container-grid">
            <div class="form_control">
              <label for="id_name"> Buyer Name </label>
              {{ form.name|as_crispy_field}}
            </div>
            <div class="form_control">
              <label for="id_shortcut"> Short Name </label>
              {{ form.shortcut|as_crispy_field}}
            </div>
            <div class="form_control">
              <label for="id_address"> Address </label>
              {{ form.address|as_crispy_field}}
            </div>
          </div>
          <div class="button_container">
            <button type="submit" class="button btn-green btn-r12" >Update Now</button>
          </div>
        </form>
      </div>
    </div>
    <div class="card-area">
      <div class="card">
        <div class="card-container">
          <h4 class="card-title"><b>New Buyer</b></h4> 
          <p class="card-description">{{newBuyer}}</p> 
        </div>
      </div>
      <div class="card">
        <div class="card-container">
          <h4 class="card-title"><b>Total Buyer</b></h4> 
          <p class="card-description">{{totalBuyer}}</p> 
        </div>
      </div>
    </div>
  </div>
  <div class="list-area">
    <table class="table"style="width:100%">
        <tr>
            <th style="width:5%">SL</th>
            <th style="width:45%">Buyer</th>
            <th style="width:15%">Shortcut</th>
            <th style="width:20%">Address</th>
            <th style="width:15%">Action</th>
          </tr>
          {% for Buyer in Buyers %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{Buyer.name}}</td>
            <td>{{Buyer.shortcut}}</td>
            <td>{{Buyer.address}}</td>
            <td><a href="{% url 'buyer-edit' Buyer.pk%}" class="button btn-green btn-r12 by-edit">Edit</a></td>
          </tr>
          {% endfor%}
        </table>
  </div>
</div>
<script src="{% static 'js/buyerListAdd.js' %}"></script>
{% endblock content %}

templates/setup/styleListAdd.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% block title %}Buyer Page{% endblock title %}
{% load crispy_forms_tags %}
{% block css %}<link rel="stylesheet" href="{% static 'css/setup/buyerListAdd.css' %}" />{% endblock css %}  
{% block content %}
<div class="buyer-add-edit">
  <div class="messages">
    {% if messages %}
    {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
    {% endif %}
  </div>
  <div class="hero_box">
    <div class="add-buyer form_box">
      <h3 class="form-title"><a href="#" class="open-button" onclick="openForm()">Add Style</a></h3>
      <div id="myForm">
          <form method="POST">
            {% csrf_token %}
          <div class="form_container-grid">
            <div class="form_control">
              <label for="id_name"> Style Name </label>
              {{ form.name|as_crispy_field}}
            </div>
            <div class="form_control">
              <label for="id_buyer">Buyer Name</label>
              {{ form.buyer|as_crispy_field}}
            </div>
            <div class="form_control">
              <label for="id_smv"> SMV </label>
              {{ form.smv|as_crispy_field}}
            </div>
          </div>
          <div class="button_container">
            <button type="submit" class="button btn-green btn-r12" >Apply Now</button>
          </div>
        </form>
      </div>
    </div>
    <div class="card-area">
      <div class="card">
        <div class="card-container">
          <h4 class="card-title"><b>New Style</b></h4> 
          <p class="card-description">{{newStyle}}</p> 
        </div>
      </div>
      <div class="card">
        <div class="card-container">
          <h4 class="card-title"><b>Total Style</b></h4> 
          <p class="card-description">{{totalStyle}}</p> 
        </div>
      </div>
    </div>
  </div>
  <div class="list-area">
    <table class="table"style="width:100%">
        <tr>
            <th style="width:5%">SL</th>
            <th style="width:45%">Style</th>
            <th style="width:15%">Buyer</th>
            <th style="width:20%">SMV</th>
            <th style="width:15%">Action</th>
          </tr>
          {% for Styles in Style %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{Styles.name}}</td>
            <td>{{Styles.buyer}}</td>
            <td>{{Styles.smv}}</td>
            <td><a href="{% url 'style-edit' Styles.pk %}" class="button btn-green btn-r12 by-edit">Edit</a></td>
          </tr>
          {% endfor%}
        </table>
  </div>
</div>
<script src="{% static 'js/buyerListAdd.js' %}"></script>
{% endblock content %}

templates/setup/styleListEdit.html
{% extends 'partials/base.html' %} 
{% load static %} 
{% block title %}Buyer Page{% endblock title %}
{% load crispy_forms_tags %}
{% block css %}
  <link rel="stylesheet" href="{% static 'css/setup/buyerListAdd.css' %}" />
  <link rel="stylesheet" href="{% static 'css/setup/buyerListEdit.css' %}" />
{% endblock css %}  
{% block content %}
<div class="buyer-add-edit">
  <div class="messages">
    {% if messages %}
    {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
    {% endif %}
  </div>
  <div class="hero_box">
    <div class="add-buyer form_box">
      <h3 class="form-title"><a href="#" class="open-button" onclick="openForm()">Update Style</a></h3>
      <div id="myForm">
          <form method="POST">
            {% csrf_token %}
          <div class="form_container-grid">
            <div class="form_control">
              <label for="id_name"> Style Name </label>
              {{ form.name|as_crispy_field}}
            </div>
            <div class="form_control">
              <label for="id_buyer">Buyer Name</label>
              {{ form.buyer}}
            </div>
            <div class="form_control">
              <label for="id_smv"> SMV </label>
              {{ form.smv}}
            </div>
          </div>
          <div class="button_container">
            <button type="submit" class="button btn-green btn-r12" >Update Now</button>
          </div>
        </form>
      </div>
    </div>
    <div class="card-area">
      <div class="card">
        <div class="card-container">
          <h4 class="card-title"><b>New Style</b></h4> 
          <p class="card-description">{{newStyle}}</p> 
        </div>
      </div>
      <div class="card">
        <div class="card-container">
          <h4 class="card-title"><b>Total Style</b></h4> 
          <p class="card-description">{{totalStyle}}</p> 
        </div>
      </div>
    </div>
  </div>
  <div class="list-area">
    <table class="table"style="width:100%">
        <tr>
            <th style="width:5%">SL</th>
            <th style="width:45%">Style</th>
            <th style="width:15%">Buyer</th>
            <th style="width:20%">SMV</th>
            <th style="width:15%">Action</th>
          </tr>
          {% for Styles in Style %}
          <tr>
            <td>{{forloop.counter}}</td>
            <td>{{Styles.name}}</td>
            <td>{{Styles.buyer}}</td>
            <td>{{Styles.smv}}</td>
            <td><a href="{% url 'style-edit' Styles.pk %}" class="button btn-green btn-r12 by-edit">Edit</a></td>
          </tr>
          {% endfor%}
        </table>
  </div>
</div>
<script src="{% static 'js/buyerListAdd.js' %}"></script>
{% endblock content %}